apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-asset-management.fullname" . }}-secrets
  labels:
    {{- include "log-asset-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "log-asset-management.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  jwt-secret: {{ .Values.config.backend.jwtSecret | quote }}
  session-secret: {{ .Values.config.backend.sessionSecret | quote }}
  {{- if .Values.config.oauth.github.clientId }}
  github-client-id: {{ .Values.config.oauth.github.clientId | quote }}
  {{- end }}
  {{- if .Values.config.oauth.github.clientSecret }}
  github-client-secret: {{ .Values.config.oauth.github.clientSecret | quote }}
  {{- end }}
  {{- if .Values.config.oauth.google.clientId }}
  google-client-id: {{ .Values.config.oauth.google.clientId | quote }}
  {{- end }}
  {{- if .Values.config.oauth.google.clientSecret }}
  google-client-secret: {{ .Values.config.oauth.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.config.oauth.apple.clientId }}
  apple-client-id: {{ .Values.config.oauth.apple.clientId | quote }}
  {{- end }}
  {{- if .Values.config.oauth.apple.clientSecret }}
  apple-client-secret: {{ .Values.config.oauth.apple.clientSecret | quote }}
  {{- end }}
